# Generated by Django 6.0.3 on 2026-03-25 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('microsoft', 'Microsoft')], max_length=20)),
                ('message_id', models.CharField(max_length=255)),
                ('from_address', models.CharField(blank=True, max_length=255)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('snippet', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('labels', models.JSONField(default=list)),
                ('has_attachments', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('processed', 'Processed'), ('ignored', 'Ignored')], default='new', max_length=20)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('order', 'Order'), ('payment', 'Payment'), ('shipping', 'Shipping'), ('refund', 'Refund'), ('subscription', 'Subscription'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('partial', 'Partial'), ('complete', 'Complete')], default='partial', max_length=20)),
                ('vendor_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('order_number', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('confidence', models.FloatField(default=0.0)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='emails.email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['user', 'status'], name='emails_emai_user_id_9f0318_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['user', 'provider', 'message_id'], name='emails_emai_user_id_7053a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='email',
            unique_together={('user', 'provider', 'message_id')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'status'], name='emails_tran_user_id_6e8753_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'type'], name='emails_tran_user_id_33898b_idx'),
        ),
    ]
