# Generated by Django 6.0.3 on 2026-03-25 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='has_list_unsubscribe',
            field=models.BooleanField(default=False),
        ),
    ]
