# Generated by Django 6.0.3 on 2026-03-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_email_has_list_unsubscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('receipt', 'Receipt'), ('order', 'Order'), ('payment', 'Payment'), ('shipping', 'Shipping'), ('refund', 'Refund'), ('cancellation', 'Cancellation'), ('subscription', 'Subscription'), ('other', 'Other')], max_length=20),
        ),
    ]
