# Generated by Django 6.0.3 on 2026-03-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_email_triage_passed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_tax_excl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='items',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
