# Generated by Django 6.0.3 on 2026-03-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_transaction_amount_tax_excl_transaction_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
