# Generated by Django 6.0.3 on 2026-03-27 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('access_token', models.TextField()),
                ('shop_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopify_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopifyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.BigIntegerField(unique=True)),
                ('order_number', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('financial_status', models.CharField(max_length=30)),
                ('fulfillment_status', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('subtotal_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_discounts', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_shipping', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_gateway', models.CharField(blank=True, max_length=100)),
                ('transaction_id_external', models.CharField(blank=True, max_length=255)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_email', models.CharField(blank=True, max_length=255)),
                ('line_items', models.JSONField(default=list)),
                ('shipping_lines', models.JSONField(default=list)),
                ('tax_lines', models.JSONField(default=list)),
                ('refunds', models.JSONField(default=list)),
                ('note', models.TextField(blank=True)),
                ('tags', models.TextField(blank=True)),
                ('created_at_shopify', models.DateTimeField()),
                ('updated_at_shopify', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='shopify_provider.shopifyconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopify_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at_shopify'],
                'indexes': [models.Index(fields=['user', 'created_at_shopify'], name='shopify_pro_user_id_2d0176_idx')],
            },
        ),
    ]
