# Generated by Django 6.0.3 on 2026-03-27 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WooCommerceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_url', models.URLField()),
                ('consumer_key', models.CharField(max_length=255)),
                ('consumer_secret', models.TextField()),
                ('shop_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='woocommerce_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WooCommerceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('woo_id', models.IntegerField(unique=True)),
                ('order_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(max_length=30)),
                ('currency', models.CharField(max_length=3)),
                ('subtotal_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_shipping', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(blank=True, max_length=100)),
                ('payment_method_title', models.CharField(blank=True, max_length=255)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('customer_id_woo', models.IntegerField(blank=True, null=True)),
                ('billing_email', models.CharField(blank=True, max_length=255)),
                ('billing_name', models.CharField(blank=True, max_length=255)),
                ('line_items', models.JSONField(default=list)),
                ('tax_lines', models.JSONField(default=list)),
                ('shipping_lines', models.JSONField(default=list)),
                ('coupon_lines', models.JSONField(default=list)),
                ('refunds_summary', models.JSONField(default=list)),
                ('date_created', models.DateTimeField()),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='woocommerce_provider.woocommerceconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='woocommerce_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
                'indexes': [models.Index(fields=['user', 'date_created'], name='woocommerce_user_id_c04958_idx')],
            },
        ),
    ]
