# Generated by Django 6.0.3 on 2026-03-27 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankFileImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=500)),
                ('file_format', models.CharField(max_length=20)),
                ('file_size', models.IntegerField(default=0)),
                ('encoding', models.CharField(blank=True, max_length=30)),
                ('separator', models.CharField(blank=True, max_length=5)),
                ('column_mapping', models.JSONField(default=dict)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('account_id', models.CharField(blank=True, max_length=255)),
                ('transactions_count', models.IntegerField(default=0)),
                ('duplicates_skipped', models.IntegerField(default=0)),
                ('raw_preview', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('counterparty', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=100)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('file_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bank_import.bankfileimport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='bank_import_user_id_621ab8_idx'), models.Index(fields=['fingerprint'], name='bank_import_fingerp_197a21_idx')],
            },
        ),
    ]
