# Generated by Django 6.0.3 on 2026-03-31 14:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('siret', models.CharField(blank=True, default='', max_length=20)),
                ('sector', models.CharField(blank=True, default='', max_length=100)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('plan1', 'Plan 1'), ('plan2', 'Plan 2')], default='free', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('brand_color', models.CharField(blank=True, default='', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('granularity', models.CharField(choices=[('invoice_payment', 'Invoice / Payment'), ('three_way', 'Three-Way'), ('line_by_line', 'Line by Line')], default='invoice_payment', max_length=20)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Correlation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invoice_data', models.JSONField(blank=True, null=True)),
                ('payment_data', models.JSONField(blank=True, null=True)),
                ('score_confiance', models.FloatField(default=0)),
                ('statut', models.CharField(choices=[('reconciled', 'Reconciled'), ('reconciled_with_alert', 'Reconciled with Alert'), ('unpaid', 'Unpaid'), ('orphan_payment', 'Orphan Payment'), ('uncertain', 'Uncertain')], default='uncertain', max_length=30)),
                ('match_criteria', models.TextField(blank=True, default='')),
                ('is_manual', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations', to='core.execution')),
            ],
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('severity', models.CharField(default='medium', max_length=20)),
                ('invoice_data', models.JSONField(blank=True, null=True)),
                ('payment_data', models.JSONField(blank=True, null=True)),
                ('amount_impact', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('correlation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='core.correlation')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='core.execution')),
            ],
            options={
                'verbose_name_plural': 'anomalies',
            },
        ),
        migrations.CreateModel(
            name='ExportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('excel', 'Excel'), ('pdf', 'PDF'), ('json', 'JSON')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready'), ('error', 'Error'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('file_url', models.URLField(blank=True, default='')),
                ('file_size', models.IntegerField(default=0)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='core.execution')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('service_type', models.CharField(choices=[('invoicing', 'Invoicing'), ('payment', 'Payment'), ('email', 'Email')], max_length=20)),
                ('provider_name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('error', 'Error'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('auth_type', models.CharField(choices=[('oauth', 'OAuth'), ('api_key', 'API Key')], max_length=20)),
                ('credentials', models.JSONField(blank=True, default=dict)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='core.company')),
            ],
            options={
                'unique_together': {('company', 'provider_name')},
            },
        ),
        migrations.AddField(
            model_name='execution',
            name='included_connections',
            field=models.ManyToManyField(blank=True, to='core.serviceconnection'),
        ),
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('company', 'user')},
            },
        ),
    ]
