# Generated by Django 6.0.3 on 2026-04-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceconnection',
            name='auth_type',
            field=models.CharField(choices=[('oauth', 'OAuth'), ('api_key', 'API Key'), ('file_upload', 'File Upload')], max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceconnection',
            name='service_type',
            field=models.CharField(choices=[('invoicing', 'Invoicing'), ('payment', 'Payment'), ('email', 'Email'), ('banking', 'Banking')], max_length=20),
        ),
    ]
