# Generated by Django 6.0.3 on 2026-03-27 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolizConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=255)),
                ('secret_key', models.TextField()),
                ('company_id', models.CharField(max_length=255)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evoliz_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvolizInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evoliz_id', models.IntegerField(unique=True)),
                ('document_number', models.CharField(max_length=100)),
                ('typedoc', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('documentdate', models.DateField()),
                ('duedate', models.DateField(blank=True, null=True)),
                ('object_label', models.TextField(blank=True)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('client_id_evoliz', models.IntegerField(blank=True, null=True)),
                ('total_vat_exclude', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_vat_include', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_to_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('items', models.JSONField(default=list)),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='evoliz_provider.evolizconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoliz_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-documentdate'],
                'indexes': [models.Index(fields=['user', 'documentdate'], name='evoliz_prov_user_id_7f6679_idx')],
            },
        ),
        migrations.CreateModel(
            name='EvolizPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evoliz_id', models.IntegerField(unique=True)),
                ('paydate', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('label', models.TextField(blank=True)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('invoice_id_evoliz', models.IntegerField(blank=True, null=True)),
                ('paytype_label', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='evoliz_provider.evolizconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoliz_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paydate'],
                'indexes': [models.Index(fields=['user', 'paydate'], name='evoliz_prov_user_id_4b590e_idx')],
            },
        ),
        migrations.CreateModel(
            name='EvolizPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evoliz_id', models.IntegerField(unique=True)),
                ('document_number', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=30)),
                ('documentdate', models.DateField()),
                ('duedate', models.DateField(blank=True, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('supplier_id_evoliz', models.IntegerField(blank=True, null=True)),
                ('total_vat_exclude', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_vat_include', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_to_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('items', models.JSONField(default=list)),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='evoliz_provider.evolizconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoliz_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-documentdate'],
                'indexes': [models.Index(fields=['user', 'documentdate'], name='evoliz_prov_user_id_8ab154_idx')],
            },
        ),
    ]
