# Generated by Django 6.0.3 on 2026-03-27 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlmaConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.TextField()),
                ('is_sandbox', models.BooleanField(default=True)),
                ('merchant_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alma_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlmaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alma_id', models.CharField(max_length=255, unique=True)),
                ('state', models.CharField(max_length=30)),
                ('processing_status', models.CharField(blank=True, max_length=30)),
                ('purchase_amount', models.IntegerField()),
                ('customer_fee', models.IntegerField(default=0)),
                ('installments_count', models.IntegerField()),
                ('kind', models.CharField(blank=True, max_length=20)),
                ('customer_email', models.CharField(blank=True, max_length=255)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('merchant_reference', models.CharField(blank=True, max_length=255)),
                ('payment_plan', models.JSONField(default=list)),
                ('refunds', models.JSONField(default=list)),
                ('amount_already_refunded', models.IntegerField(default=0)),
                ('is_completely_refunded', models.BooleanField(default=False)),
                ('payout_status', models.CharField(blank=True, max_length=30)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at_alma', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='alma_provider.almaconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alma_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at_alma'],
                'indexes': [models.Index(fields=['user', 'created_at_alma'], name='alma_provid_user_id_577e3e_idx')],
            },
        ),
    ]
