# Generated by Django 6.0.3 on 2026-03-27 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_account_id', models.CharField(max_length=255, unique=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('institution_name', models.CharField(blank=True, max_length=255)),
                ('last4', models.CharField(blank=True, max_length=4)),
                ('category', models.CharField(blank=True, choices=[('cash', 'Cash'), ('credit', 'Credit'), ('investment', 'Investment'), ('other', 'Other')], max_length=20)),
                ('subcategory', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('disconnected', 'Disconnected')], default='active', max_length=20)),
                ('permissions', models.JSONField(default=list)),
                ('balance_current', models.JSONField(blank=True, null=True)),
                ('balance_available', models.JSONField(blank=True, null=True)),
                ('balance_type', models.CharField(blank=True, max_length=10)),
                ('balance_as_of', models.DateTimeField(blank=True, null=True)),
                ('balance_refresh_status', models.CharField(blank=True, max_length=20)),
                ('ownership_data', models.JSONField(default=list)),
                ('ownership_refresh_status', models.CharField(blank=True, max_length=20)),
                ('transaction_refresh_status', models.CharField(blank=True, max_length=20)),
                ('transaction_subscribed', models.BooleanField(default=False)),
                ('last_transaction_refresh_id', models.CharField(blank=True, max_length=255)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_transaction_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('void', 'Void')], max_length=10)),
                ('transacted_at', models.DateTimeField()),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('void_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_refresh_id', models.CharField(blank=True, max_length=255)),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='stripe_financial.financialaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transacted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['user', 'status'], name='stripe_fina_user_id_e7f446_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['user', 'transacted_at'], name='stripe_fina_user_id_942930_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['account', 'transacted_at'], name='stripe_fina_account_2ae33b_idx'),
        ),
    ]
