# Generated by Django 6.0.3 on 2026-03-27 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FintectureConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=255)),
                ('app_secret', models.TextField()),
                ('is_sandbox', models.BooleanField(default=True)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fintecture_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FintectureSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_id', models.CharField(max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=30)),
                ('execution_date', models.DateField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='fintecture_provider.fintectureconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fintecture_settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-execution_date'],
            },
        ),
        migrations.CreateModel(
            name='FintecturePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=32, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('communication', models.CharField(blank=True, max_length=255)),
                ('end_to_end_id', models.CharField(blank=True, max_length=64)),
                ('execution_date', models.DateField(blank=True, null=True)),
                ('payment_scheme', models.CharField(blank=True, max_length=20)),
                ('transfer_state', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('session_type', models.CharField(blank=True, max_length=30)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('customer_id', models.CharField(blank=True, max_length=32)),
                ('bank_account_id', models.CharField(blank=True, max_length=64)),
                ('is_accepted', models.BooleanField(default=False)),
                ('has_settlement_completed', models.BooleanField(default=False)),
                ('metadata', models.JSONField(default=dict)),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fintecture_provider.fintectureconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fintecture_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-execution_date'],
                'indexes': [models.Index(fields=['user', 'execution_date'], name='fintecture__user_id_801601_idx')],
            },
        ),
    ]
