# Generated by Django 6.0.3 on 2026-03-27 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChorusProConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.TextField()),
                ('technical_user_id', models.IntegerField()),
                ('structure_id', models.IntegerField()),
                ('is_sandbox', models.BooleanField(default=True)),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='choruspro_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChorusProInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chorus_id', models.IntegerField(unique=True)),
                ('numero_facture', models.CharField(max_length=255)),
                ('type_facture', models.CharField(choices=[('FACTURE', 'Facture'), ('AVOIR', 'Avoir'), ('ACOMPTE', 'Acompte')], max_length=30)),
                ('statut', models.CharField(choices=[('DEPOSEE', 'Deposee'), ('CORRECTE', 'Correcte'), ('INCORRECTE', 'Incorrecte'), ('MISE_A_DISPOSITION_DESTINATAIRE', 'Mise a disposition destinataire'), ('PRISE_EN_CHARGE', 'Prise en charge'), ('SUSPENDUE', 'Suspendue'), ('A_RECYCLER', 'A recycler'), ('REJETEE', 'Rejetee'), ('MANDATEE', 'Mandatee'), ('MISE_EN_PAIEMENT', 'Mise en paiement'), ('COMPLETEE', 'Completee'), ('SERVICE_FAIT', 'Service fait')], max_length=50)),
                ('cadre_facturation', models.CharField(blank=True, max_length=100)),
                ('date_depot', models.DateTimeField(blank=True, null=True)),
                ('date_facture', models.DateField(blank=True, null=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_tva', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devise', models.CharField(default='EUR', max_length=3)),
                ('fournisseur_name', models.CharField(blank=True, max_length=255)),
                ('fournisseur_siret', models.CharField(blank=True, max_length=14)),
                ('destinataire_name', models.CharField(blank=True, max_length=255)),
                ('destinataire_siret', models.CharField(blank=True, max_length=14)),
                ('numero_bon_commande', models.CharField(blank=True, max_length=255)),
                ('numero_engagement', models.CharField(blank=True, max_length=255)),
                ('historique_statuts', models.JSONField(default=list)),
                ('pieces_jointes', models.JSONField(default=list)),
                ('commentaire', models.TextField(blank=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='choruspro_provider.chorusproconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choruspro_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_depot'],
                'indexes': [models.Index(fields=['user', 'date_depot'], name='choruspro_p_user_id_a684df_idx')],
            },
        ),
    ]
