# Generated by Django 6.0.3 on 2026-03-26 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powens_connection_id', models.IntegerField(unique=True)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_connections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powens_account_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('account_type', models.CharField(blank=True, max_length=50)),
                ('disabled', models.BooleanField(default=False)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='banking.bankconnection')),
            ],
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powens_transaction_id', models.IntegerField(unique=True)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('original_wording', models.CharField(max_length=500)),
                ('simplified_wording', models.CharField(blank=True, max_length=500)),
                ('transaction_type', models.CharField(blank=True, max_length=50)),
                ('coming', models.BooleanField(default=False)),
                ('card', models.CharField(blank=True, max_length=20)),
                ('counterparty_label', models.CharField(blank=True, max_length=255)),
                ('counterparty_iban', models.CharField(blank=True, max_length=34)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.bankaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PowensUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powens_user_id', models.IntegerField(unique=True)),
                ('auth_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='powens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
