# Generated by Django 6.0.3 on 2026-03-26 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_banktransaction_category_id_and_more'),
        ('emails', '0006_add_body_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('match_method', models.CharField(choices=[('exact', 'Exact'), ('fuzzy_vendor', 'Fuzzy Vendor'), ('date_offset', 'Date Offset'), ('cross_currency', 'Cross Currency'), ('reference', 'Reference')], max_length=20)),
                ('status', models.CharField(choices=[('auto', 'Auto'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='auto', max_length=20)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['user', 'date'], name='banking_ban_user_id_0a7ae2_idx'),
        ),
        migrations.AddField(
            model_name='transactionmatch',
            name='bank_transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='banking.banktransaction'),
        ),
        migrations.AddField(
            model_name='transactionmatch',
            name='email_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_matches', to='emails.transaction'),
        ),
        migrations.AddField(
            model_name='transactionmatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='transactionmatch',
            index=models.Index(fields=['user', 'status'], name='banking_tra_user_id_ef174e_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionmatch',
            index=models.Index(fields=['email_transaction'], name='banking_tra_email_t_4091fd_idx'),
        ),
    ]
