# Generated by Django 6.0.3 on 2026-03-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_transactionmatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='business_personal',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='enriched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='expense_category',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='expense_category_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='recurring_group_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='tva_deductible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='vendor_type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
