# Generated by Django 6.0.3 on 2026-03-26 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_banktransaction_business_personal_and_more'),
        ('emails', '0006_add_body_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('provider_transaction_id', models.CharField(max_length=255)),
                ('provider_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('provider_currency', models.CharField(max_length=3)),
                ('confidence', models.FloatField()),
                ('match_method', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('auto', 'Auto'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='auto', max_length=20)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('email_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_matches', to='emails.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'provider'], name='banking_pro_user_id_f3c787_idx'), models.Index(fields=['email_transaction'], name='banking_pro_email_t_a7b072_idx')],
                'unique_together': {('provider', 'provider_transaction_id')},
            },
        ),
    ]
