# Generated by Django 6.0.3 on 2026-03-27 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestaShopConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_url', models.URLField()),
                ('api_key', models.TextField()),
                ('shop_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prestashop_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrestaShopPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestashop_id', models.IntegerField(unique=True)),
                ('order_reference', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(blank=True, max_length=255)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('card_brand', models.CharField(blank=True, max_length=50)),
                ('date_add', models.DateTimeField()),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='prestashop_provider.prestashopconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestashop_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_add'],
            },
        ),
        migrations.CreateModel(
            name='PrestaShopOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prestashop_id', models.IntegerField(unique=True)),
                ('reference', models.CharField(max_length=50)),
                ('current_state', models.IntegerField()),
                ('current_state_name', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(blank=True, max_length=255)),
                ('payment_module', models.CharField(blank=True, max_length=100)),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_paid_real', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_products', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_products_wt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_shipping', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_shipping_tax_incl', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_discounts', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency_id', models.IntegerField(blank=True, null=True)),
                ('customer_id_ps', models.IntegerField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('line_items', models.JSONField(default=list)),
                ('date_add', models.DateTimeField()),
                ('date_upd', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='prestashop_provider.prestashopconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestashop_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_add'],
                'indexes': [models.Index(fields=['user', 'date_add'], name='prestashop__user_id_92e6b4_idx')],
            },
        ),
    ]
