# Generated by Django 6.0.3 on 2026-03-27 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QontoConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255)),
                ('secret_key', models.TextField()),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qonto_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QontoBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qonto_id', models.CharField(max_length=64, unique=True)),
                ('slug', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('bic', models.CharField(blank=True, max_length=11)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('balance_cents', models.BigIntegerField(default=0)),
                ('authorized_balance_cents', models.BigIntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=20)),
                ('is_main', models.BooleanField(default=False)),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qonto_bank_accounts', to=settings.AUTH_USER_MODEL)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='qonto_provider.qontoconnection')),
            ],
        ),
        migrations.CreateModel(
            name='QontoTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qonto_id', models.CharField(max_length=64, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('amount_cents', models.BigIntegerField()),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('side', models.CharField(max_length=10)),
                ('operation_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('label', models.TextField(blank=True)),
                ('counterparty_name', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('emitted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('attachment_ids', models.JSONField(default=list)),
                ('label_ids', models.JSONField(default=list)),
                ('card_last_digits', models.CharField(blank=True, max_length=4)),
                ('bank_account_id', models.CharField(blank=True, max_length=64)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at_qonto', models.DateTimeField()),
                ('updated_at_qonto', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='qonto_provider.qontoconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qonto_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-settled_at'],
                'indexes': [models.Index(fields=['user', 'settled_at'], name='qonto_provi_user_id_cd4961_idx')],
            },
        ),
    ]
