# Generated by Django 6.0.3 on 2026-03-27 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SumUpConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.TextField()),
                ('merchant_code', models.CharField(max_length=20)),
                ('merchant_name', models.CharField(blank=True, max_length=255)),
                ('default_currency', models.CharField(blank=True, max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sumup_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SumUpPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumup_id', models.IntegerField(unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('date', models.DateField()),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=30)),
                ('reference', models.CharField(blank=True, max_length=64)),
                ('transaction_code', models.CharField(blank=True, max_length=32)),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='sumup_provider.sumupconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sumup_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SumUpTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumup_id', models.CharField(max_length=64, unique=True)),
                ('transaction_code', models.CharField(blank=True, max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tip_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refunded_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('payment_type', models.CharField(blank=True, max_length=20)),
                ('entry_mode', models.CharField(blank=True, max_length=30)),
                ('card_type', models.CharField(blank=True, max_length=20)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('product_summary', models.TextField(blank=True)),
                ('installments_count', models.IntegerField(default=1)),
                ('payout_date', models.DateField(blank=True, null=True)),
                ('payout_type', models.CharField(blank=True, max_length=30)),
                ('auth_code', models.CharField(blank=True, max_length=16)),
                ('internal_id', models.BigIntegerField(blank=True, null=True)),
                ('products', models.JSONField(default=list)),
                ('vat_rates', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='sumup_provider.sumupconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sumup_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='sumup_provi_user_id_240b17_idx')],
            },
        ),
    ]
