# Generated by Django 6.0.3 on 2026-03-27 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VosFacturesConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.TextField()),
                ('account_prefix', models.CharField(max_length=255)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vosfactures_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VosFacturesClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vosfactures_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('tax_no', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('post_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vosfactures_clients', to=settings.AUTH_USER_MODEL)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='vosfactures_provider.vosfacturesconnection')),
            ],
        ),
        migrations.CreateModel(
            name='VosFacturesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vosfactures_id', models.IntegerField(unique=True)),
                ('number', models.CharField(blank=True, max_length=100)),
                ('kind', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('sell_date', models.CharField(blank=True, max_length=20)),
                ('payment_to', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('price_net', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_gross', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('income', models.BooleanField(default=True)),
                ('buyer_name', models.CharField(blank=True, max_length=255)),
                ('buyer_tax_no', models.CharField(blank=True, max_length=50)),
                ('client_id_vf', models.IntegerField(blank=True, null=True)),
                ('seller_name', models.CharField(blank=True, max_length=255)),
                ('payment_type', models.CharField(blank=True, max_length=50)),
                ('positions', models.JSONField(default=list)),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='vosfactures_provider.vosfacturesconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vosfactures_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='VosFacturesPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vosfactures_id', models.IntegerField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('invoice_id_vf', models.IntegerField(blank=True, null=True)),
                ('invoice_name', models.CharField(blank=True, max_length=255)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='vosfactures_provider.vosfacturesconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vosfactures_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
