# Generated by Django 6.0.3 on 2026-03-27 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('triage', 'Triage'), ('extraction', 'Extraction'), ('merge', 'Merge'), ('computation', 'Computation'), ('bank_correlation', 'Bank Correlation'), ('provider_correlation', 'Provider Correlation'), ('classification', 'Classification'), ('recurring', 'Recurring'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('current_pass', models.IntegerField(default=0)),
                ('state', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('stats', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
