# Generated by Django 6.0.3 on 2026-03-31 22:26

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('emails', '0006_add_body_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankFileImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='bank_imports/%Y/%m/')),
                ('file_type', models.CharField(choices=[('csv', 'Csv'), ('ofx', 'Ofx'), ('qif', 'Qif'), ('camt053', 'Camt053')], max_length=10)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('account_identifier', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsing', 'Parsing'), ('needs_confirmation', 'Needs Confirmation'), ('parsed', 'Parsed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('rows_total', models.IntegerField(default=0)),
                ('rows_imported', models.IntegerField(default=0)),
                ('rows_skipped', models.IntegerField(default=0)),
                ('parser_used', models.CharField(blank=True, default='', max_length=50)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_file_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(default='', max_length=255)),
                ('cluster_type', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('subscription', 'Subscription'), ('refund', 'Refund'), ('transfer', 'Transfer'), ('salary', 'Salary'), ('tax_payment', 'Tax Payment'), ('other', 'Other')], default='other', max_length=20)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('margin', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_tax_collected', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_tax_deductible', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('confidence', models.FloatField(default=0.0)),
                ('is_complete', models.BooleanField(default=False)),
                ('corroboration_score', models.FloatField(default=0.0)),
                ('verification_status', models.CharField(choices=[('auto', 'Auto'), ('verified', 'Verified'), ('disputed', 'Disputed')], default='auto', max_length=10)),
                ('match_reasoning', models.TextField(blank=True, default='')),
                ('evidence_summary', models.JSONField(default=dict)),
                ('created_by', models.CharField(default='ai_agent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_clusters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnifiedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_type', models.CharField(choices=[('stripe', 'Stripe'), ('mollie', 'Mollie'), ('paypal', 'Paypal'), ('bank_api', 'Bank Api'), ('bank_import', 'Bank Import'), ('email', 'Email'), ('gocardless', 'Gocardless'), ('qonto', 'Qonto'), ('shopify', 'Shopify'), ('woocommerce', 'Woocommerce'), ('prestashop', 'Prestashop'), ('manual', 'Manual')], max_length=20)),
                ('source_id', models.CharField(max_length=255)),
                ('source_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('direction', models.CharField(choices=[('inflow', 'Inflow'), ('outflow', 'Outflow')], max_length=10)),
                ('category', models.CharField(choices=[('revenue', 'Revenue'), ('expense_service', 'Expense Service'), ('expense_goods', 'Expense Goods'), ('expense_shipping', 'Expense Shipping'), ('purchase_cost', 'Purchase Cost'), ('tax', 'Tax'), ('fee', 'Fee'), ('refund', 'Refund'), ('transfer', 'Transfer'), ('salary', 'Salary'), ('other', 'Other')], default='other', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('amount_tax_excl', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('vendor_name', models.CharField(default='', max_length=255)),
                ('vendor_name_normalized', models.CharField(db_index=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('reference', models.CharField(blank=True, default='', max_length=255)),
                ('payment_method', models.CharField(blank=True, default='', max_length=100)),
                ('items', models.JSONField(blank=True, default=list)),
                ('confidence', models.FloatField(default=0.5)),
                ('completeness', models.CharField(choices=[('complete', 'Complete'), ('partial', 'Partial'), ('minimal', 'Minimal')], default='partial', max_length=10)),
                ('evidence_role', models.CharField(choices=[('primary', 'Primary'), ('confirmation', 'Confirmation'), ('enrichment', 'Enrichment'), ('contradiction', 'Contradiction')], default='primary', max_length=15)),
                ('pcg_code', models.CharField(blank=True, default='', max_length=10)),
                ('pcg_label', models.CharField(blank=True, default='', max_length=100)),
                ('business_personal', models.CharField(choices=[('business', 'Business'), ('personal', 'Personal'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('tva_deductible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='ai_agent.transactioncluster')),
                ('related_emails', models.ManyToManyField(blank=True, related_name='unified_transactions', to='emails.email')),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unified_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transactioncluster',
            index=models.Index(fields=['user', 'cluster_type'], name='ai_agent_tr_user_id_bfef78_idx'),
        ),
        migrations.AddIndex(
            model_name='transactioncluster',
            index=models.Index(fields=['user', 'verification_status'], name='ai_agent_tr_user_id_4bbe00_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedtransaction',
            index=models.Index(fields=['user', 'transaction_date'], name='ai_agent_un_user_id_4df7c1_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedtransaction',
            index=models.Index(fields=['user', 'source_type'], name='ai_agent_un_user_id_fcca16_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedtransaction',
            index=models.Index(fields=['user', 'category'], name='ai_agent_un_user_id_5a51a3_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedtransaction',
            index=models.Index(fields=['user', 'cluster'], name='ai_agent_un_user_id_9ca07d_idx'),
        ),
        migrations.AddConstraint(
            model_name='unifiedtransaction',
            constraint=models.UniqueConstraint(fields=('user', 'source_type', 'source_id'), name='unique_source_per_user'),
        ),
    ]
