# Generated by Django 6.0.3 on 2026-03-26 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.TextField()),
                ('account_email', models.CharField(blank=True, max_length=255)),
                ('is_sandbox', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayPalDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_id', models.CharField(max_length=255, unique=True)),
                ('disputed_transaction_id', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(max_length=30)),
                ('dispute_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('dispute_outcome', models.CharField(blank=True, max_length=50)),
                ('dispute_life_cycle_stage', models.CharField(blank=True, max_length=30)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='paypal_provider.paypalconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='PayPalInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_id', models.CharField(max_length=255, unique=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(max_length=30)),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('merchant_memo', models.TextField(blank=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('recipient_email', models.CharField(blank=True, max_length=255)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payments', models.JSONField(default=list)),
                ('refunds', models.JSONField(default=list)),
                ('line_items', models.JSONField(default=list)),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='paypal_provider.paypalconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='PayPalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('event_code', models.CharField(blank=True, max_length=10)),
                ('transaction_status', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('payer_email', models.CharField(blank=True, max_length=255)),
                ('payer_name', models.CharField(blank=True, max_length=255)),
                ('payer_id', models.CharField(blank=True, max_length=255)),
                ('protection_eligibility', models.CharField(blank=True, max_length=50)),
                ('invoice_id', models.CharField(blank=True, max_length=255)),
                ('custom_field', models.TextField(blank=True)),
                ('initiation_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='paypal_provider.paypalconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paypal_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-initiation_date'],
                'indexes': [models.Index(fields=['user', 'initiation_date'], name='paypal_prov_user_id_44a357_idx')],
            },
        ),
    ]
