# Generated by Django 6.0.3 on 2026-03-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_provider', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paypalconnection',
            old_name='client_secret',
            new_name='access_token',
        ),
        migrations.RemoveField(
            model_name='paypalconnection',
            name='client_id',
        ),
        migrations.AddField(
            model_name='paypalconnection',
            name='paypal_user_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paypalconnection',
            name='refresh_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paypalconnection',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
