# Generated by Django 6.0.3 on 2026-03-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_provider', '0002_rename_client_secret_paypalconnection_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paypalconnection',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='paypalconnection',
            name='paypal_user_id',
        ),
        migrations.RemoveField(
            model_name='paypalconnection',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='paypalconnection',
            name='token_expires_at',
        ),
        migrations.AddField(
            model_name='paypalconnection',
            name='client_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paypalconnection',
            name='client_secret',
            field=models.TextField(default=''),
        ),
    ]
