# Generated by Django 6.0.3 on 2026-03-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_provider', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripeconnection',
            old_name='api_key',
            new_name='access_token',
        ),
        migrations.AddField(
            model_name='stripeconnection',
            name='refresh_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stripeconnection',
            name='scope',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
