# Generated by Django 6.0.3 on 2026-03-27 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPlugConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.TextField()),
                ('is_live', models.BooleanField(default=False)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payplug_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayPlugRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payplug_id', models.CharField(max_length=255, unique=True)),
                ('payment_id', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at_payplug', models.DateTimeField()),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payplug_provider.payplugconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payplug_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at_payplug'],
            },
        ),
        migrations.CreateModel(
            name='PayPlugPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payplug_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.IntegerField()),
                ('amount_refunded', models.IntegerField(default=0)),
                ('currency', models.CharField(max_length=3)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_refunded', models.BooleanField(default=False)),
                ('is_3ds', models.BooleanField(null=True)),
                ('description', models.TextField(blank=True)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('card_brand', models.CharField(blank=True, max_length=20)),
                ('card_country', models.CharField(blank=True, max_length=2)),
                ('card_exp_month', models.IntegerField(blank=True, null=True)),
                ('card_exp_year', models.IntegerField(blank=True, null=True)),
                ('billing_email', models.CharField(blank=True, max_length=255)),
                ('billing_first_name', models.CharField(blank=True, max_length=255)),
                ('billing_last_name', models.CharField(blank=True, max_length=255)),
                ('failure_code', models.CharField(blank=True, max_length=100)),
                ('failure_message', models.TextField(blank=True)),
                ('installment_plan_id', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at_payplug', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payplug_provider.payplugconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payplug_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at_payplug'],
                'indexes': [models.Index(fields=['user', 'created_at_payplug'], name='payplug_pro_user_id_898c67_idx')],
            },
        ),
    ]
