# Generated by Django 6.0.3 on 2026-03-27 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoCardlessConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('environment', models.CharField(default='sandbox', max_length=10)),
                ('creditor_id', models.CharField(blank=True, max_length=255)),
                ('creditor_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gocardless_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoCardlessMandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gocardless_id', models.CharField(max_length=255, unique=True)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(max_length=30)),
                ('scheme', models.CharField(blank=True, max_length=30)),
                ('next_possible_charge_date', models.DateField(blank=True, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=255)),
                ('customer_bank_account_id', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at_gocardless', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandates', to='gocardless_provider.gocardlessconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gocardless_mandates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at_gocardless'],
            },
        ),
        migrations.CreateModel(
            name='GoCardlessPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gocardless_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.IntegerField()),
                ('amount_refunded', models.IntegerField(default=0)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=30)),
                ('charge_date', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scheme', models.CharField(blank=True, max_length=30)),
                ('retry_if_possible', models.BooleanField(default=True)),
                ('mandate_id', models.CharField(blank=True, max_length=255)),
                ('subscription_id', models.CharField(blank=True, max_length=255)),
                ('payout_id', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at_gocardless', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='gocardless_provider.gocardlessconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gocardless_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at_gocardless'],
            },
        ),
        migrations.CreateModel(
            name='GoCardlessPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gocardless_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('deducted_fees', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=20)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('payout_type', models.CharField(blank=True, max_length=20)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at_gocardless', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='gocardless_provider.gocardlessconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gocardless_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at_gocardless'],
            },
        ),
        migrations.CreateModel(
            name='GoCardlessRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gocardless_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=30)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('payment_id', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at_gocardless', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='gocardless_provider.gocardlessconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gocardless_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at_gocardless'],
            },
        ),
        migrations.CreateModel(
            name='GoCardlessSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gocardless_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=30)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('interval', models.IntegerField(default=1)),
                ('interval_unit', models.CharField(blank=True, max_length=10)),
                ('day_of_month', models.IntegerField(blank=True, null=True)),
                ('mandate_id', models.CharField(blank=True, max_length=255)),
                ('upcoming_payments', models.JSONField(default=list)),
                ('metadata', models.JSONField(default=dict)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at_gocardless', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='gocardless_provider.gocardlessconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gocardless_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at_gocardless'],
            },
        ),
    ]
