# Generated by Django 6.0.3 on 2026-03-26 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MollieConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.TextField()),
                ('organization_id', models.CharField(blank=True, max_length=255)),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mollie_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MollieInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mollie_id', models.CharField(max_length=255, unique=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('vat_number', models.CharField(blank=True, max_length=50)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=30)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_url', models.URLField(blank=True)),
                ('lines', models.JSONField(default=list)),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='mollie_provider.mollieconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mollie_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='MollieRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mollie_id', models.CharField(max_length=255, unique=True)),
                ('payment_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('settlement_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('created_at_mollie', models.DateTimeField()),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='mollie_provider.mollieconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mollie_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at_mollie'],
            },
        ),
        migrations.CreateModel(
            name='MollieSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mollie_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(max_length=30)),
                ('periods', models.JSONField(default=dict)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at_mollie', models.DateTimeField()),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='mollie_provider.mollieconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mollie_settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at_mollie'],
            },
        ),
        migrations.CreateModel(
            name='MolliePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mollie_id', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('settlement_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('settlement_currency', models.CharField(blank=True, max_length=3)),
                ('status', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('method', models.CharField(blank=True, max_length=30)),
                ('card_holder', models.CharField(blank=True, max_length=255)),
                ('card_number', models.CharField(blank=True, max_length=20)),
                ('card_brand', models.CharField(blank=True, max_length=20)),
                ('card_country', models.CharField(blank=True, max_length=2)),
                ('card_security', models.CharField(blank=True, max_length=20)),
                ('ideal_consumer_name', models.CharField(blank=True, max_length=255)),
                ('ideal_consumer_account', models.CharField(blank=True, max_length=34)),
                ('ideal_consumer_bic', models.CharField(blank=True, max_length=11)),
                ('bank_transfer_reference', models.CharField(blank=True, max_length=255)),
                ('redirect_url', models.URLField(blank=True)),
                ('webhook_url', models.URLField(blank=True)),
                ('order_id', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('locale', models.CharField(blank=True, max_length=10)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('created_at_mollie', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='mollie_provider.mollieconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mollie_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at_mollie'],
                'indexes': [models.Index(fields=['user', 'created_at_mollie'], name='mollie_prov_user_id_5dc690_idx')],
            },
        ),
    ]
