# Generated by Django 6.0.3 on 2026-03-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mollie_provider', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mollieconnection',
            old_name='api_key',
            new_name='access_token',
        ),
        migrations.AddField(
            model_name='mollieconnection',
            name='refresh_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mollieconnection',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
